// AUTO-GENERATED from src/data/products.ts. Do not edit by hand.
export const categories = [
  "Todos los Productos Congelados",
  "Empanadas",
  "Tequeños",
  "PandeBono",
  "Buñuelos",
  "Arepas",
  "Chorizos",
  "Embutidos",
  "Hojaldres",
  "Combos",
  "Extras"
] as const;
export const products = [
  {
    "id": "1",
    "slug": "empanadas-grandes-pack-6",
    "name": "Empanadas Grandes Ternera x6 und",
    "category": "Empanadas",
    "description": "🧊 CONGELADAS · Empanadas colombianas grandes de 13,5 cm. Masa crujiente de maíz por fuera, jugosas por dentro. Ideales para toda la familia.",
    "ingredients": "Masa 100% maíz molido, rellenas de carne de Vacuno 🥩 sal. patata cocida y un sofrito tradicional.",
    "preparation": " Freír en aceite a 180°C por 12 min, aproximadamente. No hace falta descongelar el producto para freírlo. ",
    "conservation": "Conservar congelado a -18°C. No recongelar una vez descongelado.",
    "price": 10.9,
    "originalPrice": null,
    "memberPrice": 8.9,
    "packSize": "6 unidades",
    "weight": "450 g",
    "format": "13,5 cm (6 unidades)",
    "soldOut": false,
    "badge": null
  },
  {
    "id": "2",
    "slug": "empanadas-grandes-pack-10",
    "name": "Empanadas Grandes de Carne Ternera      \nx10 und",
    "category": "Empanadas",
    "description": "🧊 CONGELADAS · Pack de 10 empanadas colombianas grandes de 13,5 cm. Perfectas para reuniones y celebraciones familiares.",
    "ingredients": "Masa 100% maíz molido, rellenas de carne de Vacuno 🥩 sal. patata cocida y un sofrito tradicional.",
    "preparation": " Freír en aceite a 180°C por 12 min, aproximadamente. No hace falta descongelar el producto para freírlo. ",
    "conservation": "Conservar congelado a -18°C. No recongelar una vez descongelado.",
    "price": 17.9,
    "originalPrice": null,
    "memberPrice": 16.99,
    "packSize": "10 unidades",
    "weight": "750 g",
    "format": "13,5 cm (10 unidades)",
    "soldOut": false,
    "badge": "top"
  },
  {
    "id": "25",
    "slug": "empanadas-grandes-pollo-pack-10",
    "name": "Empanadas Grandes de Pollo x10 und",
    "category": "Empanadas",
    "description": "🧊 CONGELADAS · Pack de 10 empanadas colombianas grandes de pollo mechado. Masa crujiente de maíz 100% y relleno jugoso de pollo desmechado.",
    "ingredients": "Masa 100% maíz molido, rellenas de Pollo, 🐓 sal. patata cocida y un sofrito tradicional.",
    "preparation": " Freír en aceite a 180°C por 12 min, aproximadamente. No hace falta descongelar el producto para freírlo. ",
    "conservation": "Conservar congelado a -18°C. No recongelar una vez descongelado.",
    "price": 16.99,
    "originalPrice": 17.9,
    "memberPrice": 16.49,
    "packSize": "10 unidades",
    "weight": "750 g",
    "format": "13,5 cm (10 unidades)",
    "soldOut": false,
    "badge": "oferta"
  },
  {
    "id": "8",
    "slug": "empanadas-cocteleras-pack-17-pollo",
    "name": "Empanadas de POLLO Pequeñas Cocteleras x17 und",
    "category": "Empanadas",
    "description": "🧊 CONGELADAS · Mini empanadas colombianas tipo cóctel de 8 cm. Perfectas como aperitivo o snack. Tamaño bocado, sabor gigante.",
    "ingredients": "Masa 100% maíz molido, rellenas de Pollo, 🐓 sal. patata cocida y un sofrito tradicional.",
    "preparation": "Freír en aceite a 180°C por 12 min, aproximadamente. No hace falta descongelar el producto para freírlo.",
    "conservation": "Conservar congelado a -18°C. No recongelar una vez descongelado.",
    "price": 14.9,
    "originalPrice": null,
    "memberPrice": 13.99,
    "packSize": "17 unidades",
    "weight": "510 g",
    "format": "8 cm (17 unidades)",
    "soldOut": false,
    "badge": "nuevo"
  },
  {
    "id": "26",
    "slug": "empanadas-cocteleras-pack-17-ternera",
    "name": "Empanadas de Ternera Carne Pequeñas Cocteleras x17 und",
    "category": "Empanadas",
    "description": "🧊 CONGELADAS · Mini empanadas colombianas tipo cóctel de 8 cm. Perfectas como aperitivo o snack. Tamaño bocado, sabor gigante.",
    "ingredients": "Masa 100% maíz molido, rellenas de carne de Vacuno 🥩 sal. patata cocida y un sofrito tradicional.",
    "preparation": "Freír en aceite a 180°C por 12 min, aproximadamente. No hace falta descongelar el producto para freírlo.",
    "conservation": "Conservar congelado a -18°C. No recongelar una vez descongelado.",
    "price": 14.9,
    "originalPrice": null,
    "memberPrice": 13.99,
    "packSize": "17 unidades",
    "weight": "510 g",
    "format": "8 cm (17 unidades)",
    "soldOut": false,
    "badge": "nuevo"
  },
  {
    "id": "7",
    "slug": "arepas-queso-pack-6",
    "name": "Arepa Rellena de Queso Mozzarella x5 und",
    "category": "Arepas",
    "description": "🧊 CONGELADAS · Arepas de maíz rellenas de queso mozzarella fundido. La base de la cocina colombiana y venezolana. 5 unidades por paquete.",
    "ingredients": "Harina de maíz precocida, queso mozzarella, mantequilla, sal, agua.",
    "preparation": "Plancha/sartén: 4 min por lado a fuego medio. Horno: 200°C por 12 min. Air fryer: 180°C por 10 min.",
    "conservation": "Conservar congelado a -18°C. No recongelar una vez descongelado.",
    "price": 6.9,
    "originalPrice": null,
    "memberPrice": 6.1,
    "packSize": "5 unidades",
    "weight": "700 g",
    "format": "5 unidades",
    "soldOut": false,
    "badge": "oferta"
  },
  {
    "id": "15",
    "slug": "arepa-chocolo-queso-pack-4",
    "name": "Arepa de Chócolo con Queso Colombiana x4 und",
    "category": "Arepas",
    "description": "🧊 CONGELADA · Arepa de chócolo (hecha con maíz tierno molido) Rellena con queso latino, de sabor suave y un toque dulcecito, ideal para desayuno o merienda. Producto ultracongelado a -18°C para preservar todo su sabor y textura artesanal. Llega a tu casa en perfecto estado, listo para que lo prepares cuando quieras. Sin conservantes artificiales.",
    "ingredients": "Maíz tierno (chócolo), queso latino, mantequilla, sal, azúcar.",
    "preparation": "Plancha/sartén: 4-5 min por lado a fuego medio. Horno: 200°C por 12 min.",
    "conservation": "Conservar congelado a -18°C. No recongelar una vez descongelado.",
    "price": 7.7,
    "originalPrice": null,
    "memberPrice": 7.1,
    "packSize": "4 unidades",
    "weight": "500 g",
    "format": "4 unidades",
    "soldOut": false,
    "badge": "nuevo"
  },
  {
    "id": "16",
    "slug": "arepa-artesanal-rellenar-pack-6",
    "name": "Arepa Artesanal para Rellenar x6 und",
    "category": "Arepas",
    "description": "🧊 CONGELADA · Arepa artesanal para rellenar de Dcarnilsa, con textura firme y sabor neutro. Paquete de 6 unidades, ideal para recetas rellenas y uso profesional.",
    "ingredients": "Harina de maíz precocida, agua, sal.",
    "preparation": "Plancha/sartén: 4 min por lado a fuego medio. Horno: 200°C por 12 min. Air fryer: 180°C por 10 min.",
    "conservation": "Conservar congelado a -18°C. No recongelar una vez descongelado.",
    "price": 3.9,
    "originalPrice": null,
    "memberPrice": 3.2,
    "packSize": "6 unidades",
    "weight": "800 g",
    "format": "6 unidades",
    "soldOut": true,
    "badge": null
  },
  {
    "id": "10",
    "slug": "chorizo-santarosano-pack-10",
    "name": "Chorizo Pequeño Santarosano x10 und",
    "category": "Chorizos",
    "description": "🧊 CONGELADO · Auténtico chorizo colombiano santarosano de 7,5 cm. Pack de 10 unidades. Sabor tradicional ahumado, perfecto para asar a la parrilla.",
    "ingredients": "Carne de cerdo, especias naturales, ajo, cebolla, comino, sal, tripa natural.",
    "preparation": "Parrilla/plancha: 8-10 min a fuego medio. Horno: 200°C por 15 min. Sartén: 6-8 min.",
    "conservation": "Conservar congelado a -18°C. No recongelar una vez descongelado.",
    "price": 7.9,
    "originalPrice": null,
    "memberPrice": 7.1,
    "packSize": "10 unidades",
    "weight": "500 g",
    "format": "7,5 cm (10 und)",
    "soldOut": false,
    "badge": "top"
  },
  {
    "id": "11",
    "slug": "chorizo-xl-pack-5",
    "name": "Chorizo XL Santarosano x5 und",
    "category": "Chorizos",
    "description": "🧊 CONGELADO · Chorizo colombiano santarosano tamaño XL de 22 cm. Pack de 5 unidades. Ideal para asados y parrilladas.",
    "ingredients": "Carne de cerdo, especias naturales, ajo, cebolla, comino, sal, tripa natural.",
    "preparation": "Parrilla/plancha: 12-15 min a fuego medio. Horno: 200°C por 20 min.",
    "conservation": "Conservar congelado a -18°C. No recongelar una vez descongelado.",
    "price": 12.9,
    "originalPrice": null,
    "memberPrice": 11.99,
    "packSize": "5 unidades",
    "weight": "800–1000 g",
    "format": "22 cm (5 und)",
    "soldOut": false,
    "badge": "nuevo"
  },
  {
    "id": "12",
    "slug": "salchichon-cervecero",
    "name": "Salchichón Cervecero",
    "category": "Embutidos",
    "description": "🧊 CONGELADO · Salchichón cervecero colombiano de 27,5 cm. El acompañante perfecto para una cerveza fría. Auténtico sabor D'Carnilsa.",
    "ingredients": "Carne de cerdo, carne de res, especias, sal, conservantes permitidos.",
    "preparation": "Freír en rodajas: 3-4 min por lado. Plancha: 5 min. Ideal como acompañamiento o snack.",
    "conservation": "Conservar congelado a -18°C. No recongelar una vez descongelado.",
    "price": 8.5,
    "originalPrice": null,
    "memberPrice": 7,
    "packSize": "1 unidad",
    "weight": "580 g",
    "format": "27,5 cm",
    "soldOut": false,
    "badge": null
  },
  {
    "id": "13",
    "slug": "salchicha-ranchera-pack-10",
    "name": "Salchicha Ranchera Ahumada x10 und",
    "category": "Embutidos",
    "description": "🧊 CONGELADO · Salchichas rancheras ahumadas colombianas de 11 cm. Pack de 10 unidades. Sabor ahumado auténtico marca D'Carnilsa.",
    "ingredients": "Carne de cerdo, carne de res, especias, sal, humo natural, conservantes permitidos.",
    "preparation": "Hervir: 5 min. Freír/plancha: 4-5 min. Ideal con arepa y hogao.",
    "conservation": "Conservar congelado a -18°C. No recongelar una vez descongelado.",
    "price": 7.5,
    "originalPrice": null,
    "memberPrice": 6,
    "packSize": "10 unidades",
    "weight": "400 g",
    "format": "11 cm (10 und)",
    "soldOut": false,
    "badge": null
  },
  {
    "id": "14",
    "slug": "salami-latino",
    "name": "Salami Latino",
    "category": "Embutidos",
    "description": "🧊 CONGELADO · Salami latino estilo dominicano de 15 cm. Versátil para sándwiches, acompañamientos o frito. Marca Rivera Super Especial.",
    "ingredients": "Carne de cerdo, carne de res, especias, sal, conservantes permitidos.",
    "preparation": "Cortar en rodajas y freír: 2-3 min por lado. Ideal frito con queso o en sándwich.",
    "conservation": "Conservar congelado a -18°C. No recongelar una vez descongelado.",
    "price": 7.9,
    "originalPrice": null,
    "memberPrice": 6.5,
    "packSize": "1 unidad",
    "weight": "500 g",
    "format": "15 cm",
    "soldOut": false,
    "badge": null
  },
  {
    "id": "5",
    "slug": "pandebonos-pack-6",
    "name": "Pandebono Colombiano x6 und",
    "category": "PandeBono",
    "description": "🧊 CONGELADO · Bollitos de yuca y queso, esponjosos y con ese sabor colombiano inconfundible. Perfectos para el desayuno o la merienda.",
    "ingredients": "Almidón de yuca, queso costeño, huevo, mantequilla, sal.",
    "preparation": "Horno: 180°C por 18 min. Air fryer: 170°C por 15 min.",
    "conservation": "Conservar congelado a -18°C. No recongelar una vez descongelado.",
    "price": 7.9,
    "originalPrice": null,
    "memberPrice": 6.5,
    "packSize": "6 unidades",
    "weight": "360 g",
    "format": "6 und",
    "soldOut": false,
    "badge": null
  },
  {
    "id": "4",
    "slug": "tequenos-pack-14",
    "name": "Tequeños de Queso - Pack 14",
    "category": "Tequeños",
    "description": "🧊 CONGELADO · Crujientes palitos de masa rellenos de queso fundente. El snack venezolano más adictivo.",
    "ingredients": "Harina de trigo, queso semiduro, mantequilla, huevo, sal, azúcar.",
    "preparation": "Horno: 190°C por 12 min. Air fryer: 180°C por 10 min. Freír: aceite a 180°C por 4 min.",
    "conservation": "Conservar congelado a -18°C. No recongelar una vez descongelado.",
    "price": 14.9,
    "originalPrice": null,
    "memberPrice": 12.99,
    "packSize": "14 unidades",
    "weight": null,
    "format": null,
    "soldOut": true,
    "badge": null
  },
  {
    "id": "6",
    "slug": "bunuelos-pack-6",
    "name": "Buñuelos Colombianos - Pack 6",
    "category": "Buñuelos",
    "description": "🧊 CONGELADO · Bolitas de queso fritas, crujientes por fuera y suaves por dentro. Tradición colombiana en cada bocado.",
    "ingredients": "Almidón de maíz, queso fresco, huevo, azúcar, sal, polvo de hornear.",
    "preparation": "Freír: aceite a 170°C por 6 min (dorar por todos los lados). Horno: 190°C por 15 min.",
    "conservation": "Conservar congelado a -18°C. No recongelar una vez descongelado.",
    "price": 7.7,
    "originalPrice": null,
    "memberPrice": 14.99,
    "packSize": "6 unidades",
    "weight": null,
    "format": null,
    "soldOut": true,
    "badge": null
  },
  {
    "id": "20",
    "slug": "combo-1-empanadas-pequenas-fritas",
    "name": "Combo Uno\nmás 17 empanadas pequeñas fritas",
    "category": "Combos",
    "description": "🔥 LISTAS PARA CONSUMIR · Combo Uno: más 17 empanadas pequeñas fritas, listas para disfrutar. Incluye domicilio en Zaragoza capital.",
    "ingredients": "Masa 100% maíz molido, rellenas de carne de Vacuno /pollo, patata cocida, cebolla, ajo, comino, sal.",
    "preparation": "¡Ya vienen fritas y listas! Solo calentar si lo deseas: microondas 1 min o horno 5 min a 180°C.",
    "conservation": "Consumir en el día. Se pueden recalentar.",
    "price": 19.99,
    "originalPrice": null,
    "memberPrice": 17.9,
    "packSize": "17 unidades",
    "weight": null,
    "format": null,
    "soldOut": false,
    "badge": null
  },
  {
    "id": "21",
    "slug": "combo-2-empanadas-grandes-fritas",
    "name": "Combo Dos\nmás 10 empanadas grandes fritas",
    "category": "Combos",
    "description": "🔥 LISTAS PARA CONSUMIR · Combo Dos: más 10 empanadas grandes fritas, listas para disfrutar. Incluye domicilio en Zaragoza capital.",
    "ingredients": "Masa 100% maíz molido, rellenas de carne de Vacuno /pollo, patata cocida, cebolla, ajo, comino, sal.",
    "preparation": "¡Ya vienen fritas y listas! Solo calentar si lo deseas: microondas 1 min o horno 5 min a 180°C.",
    "conservation": "Consumir en el día. Se pueden recalentar.",
    "price": 22.99,
    "originalPrice": 23.9,
    "memberPrice": 20.9,
    "packSize": "10 unidades",
    "weight": null,
    "format": null,
    "soldOut": false,
    "badge": "oferta"
  },
  {
    "id": "22",
    "slug": "combo-3-mixto-fritas",
    "name": "Combo Tres Mixto\n10 empanadas grandes más 17 pequeñas fritas",
    "category": "Combos",
    "description": "🔥 LISTAS PARA CONSUMIR · Combo Tres Mixto: 10 empanadas grandes más 17 pequeñas fritas, listas para disfrutar. Incluye domicilio en Zaragoza capital.",
    "ingredients": "Masa 100% maíz molido, rellenas de carne de Vacuno /pollo, patata cocida, cebolla, ajo, comino, sal.",
    "preparation": "¡Ya vienen fritas y listas! Solo calentar si lo deseas.",
    "conservation": "Consumir en el día. Se pueden recalentar.",
    "price": 29.99,
    "originalPrice": null,
    "memberPrice": 27,
    "packSize": "27 unidades",
    "weight": null,
    "format": null,
    "soldOut": false,
    "badge": "oferta"
  },
  {
    "id": "23",
    "slug": "combo-4-empanadas-pequenas-fritas",
    "name": "Combo Cuatro\nmás 51 empanadas pequeñas fritas",
    "category": "Combos",
    "description": "🔥 LISTAS PARA CONSUMIR · Combo Cuatro: más 51 empanadas pequeñas fritas, perfecto para fiestas y eventos. Incluye domicilio en Zaragoza capital.",
    "ingredients": "Masa 100% maíz molido, rellenas de carne de Vacuno /pollo, patata cocida, cebolla, ajo, comino, sal.",
    "preparation": "¡Ya vienen fritas y listas! Solo calentar si lo deseas.",
    "conservation": "Consumir en el día. Se pueden recalentar.",
    "price": 46.99,
    "originalPrice": null,
    "memberPrice": 39.9,
    "packSize": "51 unidades",
    "weight": null,
    "format": null,
    "soldOut": false,
    "badge": null
  },
  {
    "id": "24",
    "slug": "combo-xxl-mixto-salami-arepas",
    "name": "Combo Cinco\n10 empanadas grandes, salami, arepas y salsas",
    "category": "Combos",
    "description": "🔥 LISTAS PARA CONSUMIR · Combo Cinco: 10 empanadas grandes, salami latino, arepas de queso y salsas de ají. Incluye domicilio en Zaragoza capital.",
    "ingredients": "Masa 100% maíz molido, rellenas de carne de Vacuno /pollo, patata cocida, cebolla, ajo, comino, sal.",
    "preparation": "¡Ya vienen fritas y listas! Solo calentar si lo deseas.",
    "conservation": "Consumir en el día. Se pueden recalentar.",
    "price": 39.99,
    "originalPrice": null,
    "memberPrice": 35.99,
    "packSize": "30+ unidades",
    "weight": null,
    "format": null,
    "soldOut": false,
    "badge": "nuevo"
  },
  {
    "id": "29",
    "slug": "combo-valluno-champus-empanadas",
    "name": "Combo Valluno\nchampús, 2 empanadas y chorizo",
    "category": "Combos",
    "description": "🔥 OFERTA ESPECIAL · Auténtico Combo Valluno: champús tradicional, 2 empanadas grandes de ternera recién fritas y chorizo santarrosano a la parrilla. Sabor 100% colombiano del Valle del Cauca.",
    "ingredients": "Champús: maíz, lulo, piña, panela, canela, hojas de naranjo agrio. Empanadas: harina de maíz, carne de Vacuno, papa, cebolla, ajo, comino, sal. Chorizo: carne de cerdo, especias naturales, ajo, comino, sal.",
    "preparation": "¡Listo para disfrutar! Champús servir frío. Empanadas y chorizo calentar 1 min en microondas o 5 min en horno a 180°C.",
    "conservation": "Consumir en el día. Mantener champús refrigerado.",
    "price": 12.99,
    "originalPrice": null,
    "memberPrice": 11.99,
    "packSize": "1 combo (champús + 2 empanadas + chorizo)",
    "weight": null,
    "format": null,
    "soldOut": true,
    "badge": "oferta"
  },
  {
    "id": "27",
    "slug": "pastel-gloria",
    "name": "Pastel Gloria D'Carnilsa",
    "category": "Hojaldres",
    "description": "🧊 CONGELADO · Pastel Gloria D'Carnilsa, hojaldre tradicional colombiano relleno, suave y dorado. Ideal para el desayuno o la merienda.",
    "ingredients": "Harina de trigo, mantequilla, huevo, azúcar, relleno tradicional, sal.",
    "preparation": "Horno: 180°C por 15-18 min. Air fryer: 170°C por 12 min.",
    "conservation": "Conservar congelado a -18°C. No recongelar una vez descongelado.",
    "price": 14.9,
    "originalPrice": null,
    "memberPrice": 13.5,
    "packSize": "6 unidades",
    "weight": null,
    "format": null,
    "soldOut": false,
    "badge": "nuevo"
  },
  {
    "id": "28",
    "slug": "chicharron-dulce-guayaba",
    "name": "Chicharrón de Dulce de Guayaba D'Carnilsa",
    "category": "Hojaldres",
    "description": "🧊 CONGELADO · Chicharrón de hojaldre D'Carnilsa relleno de dulce de guayaba. Crujiente por fuera y dulce por dentro, un clásico colombiano.",
    "ingredients": "Harina de trigo, mantequilla, huevo, dulce de guayaba, azúcar, sal.",
    "preparation": "Horno: 180°C por 15 min. Air fryer: 170°C por 12 min.",
    "conservation": "Conservar congelado a -18°C. No recongelar una vez descongelado.",
    "price": 10.5,
    "originalPrice": null,
    "memberPrice": 9.5,
    "packSize": "1 paquete",
    "weight": null,
    "format": null,
    "soldOut": false,
    "badge": "nuevo"
  }
] as const;
