// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
import { products } from "npm:@/data/products";
var list_products_default = defineTool({
  name: "list_products",
  title: "Listar productos MaxRico",
  description: "Devuelve el cat\xE1logo de productos artesanales colombianos (empanadas, teque\xF1os, PandeBono, arepas, chorizos, etc.) con precio normal, precio socio y disponibilidad.",
  inputSchema: {
    category: z.string().optional().describe("Filtro opcional por categor\xEDa (ej: Empanadas, PandeBono, Arepas)."),
    onlyAvailable: z.boolean().optional().describe("Si es true, excluye productos agotados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, onlyAvailable }) => {
    const filtered = products.filter((p) => {
      if (category && p.category.toLowerCase() !== category.toLowerCase()) return false;
      if (onlyAvailable && p.soldOut) return false;
      return true;
    });
    const rows = filtered.map((p) => ({
      id: p.id,
      slug: p.slug,
      name: p.name,
      category: p.category,
      price_eur: p.price,
      member_price_eur: p.memberPrice,
      pack_size: p.packSize,
      weight: p.weight ?? null,
      sold_out: !!p.soldOut
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { products: rows }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { products as products2 } from "npm:@/data/products";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Detalle de producto",
  description: "Devuelve la ficha completa de un producto MaxRico por slug o id: descripci\xF3n, ingredientes, preparaci\xF3n, conservaci\xF3n, precios y disponibilidad.",
  inputSchema: {
    slugOrId: z2.string().min(1).describe("Slug o id del producto.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slugOrId }) => {
    const key = slugOrId.toLowerCase();
    const p = products2.find(
      (x) => x.slug.toLowerCase() === key || x.id.toLowerCase() === key
    );
    if (!p) {
      return {
        content: [{ type: "text", text: `No se encontr\xF3 ning\xFAn producto con "${slugOrId}".` }],
        isError: true
      };
    }
    const row = {
      id: p.id,
      slug: p.slug,
      name: p.name,
      category: p.category,
      description: p.description,
      ingredients: p.ingredients,
      preparation: p.preparation,
      conservation: p.conservation,
      price_eur: p.price,
      original_price_eur: p.originalPrice ?? null,
      member_price_eur: p.memberPrice,
      pack_size: p.packSize,
      weight: p.weight ?? null,
      format: p.format ?? null,
      sold_out: !!p.soldOut,
      badge: p.badge ?? null,
      url: `https://maxrico.es/producto/${p.slug}`
    };
    return {
      content: [{ type: "text", text: JSON.stringify(row, null, 2) }],
      structuredContent: { product: row }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { categories, products as products3 } from "npm:@/data/products";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "Listar categor\xEDas",
  description: "Devuelve las categor\xEDas del cat\xE1logo MaxRico y el n\xFAmero de productos en cada una.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const counts = categories.map((c) => ({
      category: c,
      count: products3.filter((p) => p.category === c).length
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(counts, null, 2) }],
      structuredContent: { categories: counts }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "maxrico-mcp",
  title: "MaxRico \u2014 Cat\xE1logo",
  version: "0.1.0",
  instructions: "Herramientas de solo lectura del cat\xE1logo de MaxRico (gastronom\xEDa artesanal colombiana, 100% ma\xEDz molido, sin gluten). Usa list_categories y list_products para explorar el cat\xE1logo, y get_product para la ficha completa. Los pedidos se hacen en https://maxrico.es o por WhatsApp +34 695798632.",
  tools: [list_products_default, get_product_default, list_categories_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
