// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/catalog-data.ts
var categories = [
  "Todos los Productos Congelados",
  "Empanadas",
  "Teque\xF1os",
  "PandeBono",
  "Bu\xF1uelos",
  "Arepas",
  "Chorizos",
  "Embutidos",
  "Hojaldres",
  "Combos"
];
var products = [
  {
    "id": "1",
    "slug": "empanadas-grandes-pack-6",
    "name": "Empanadas Grandes Ternera x6 und",
    "category": "Empanadas",
    "description": "\u{1F9CA} CONGELADAS \xB7 Empanadas colombianas grandes de 13,5 cm. Masa crujiente de ma\xEDz por fuera, jugosas por dentro. Ideales para toda la familia.",
    "ingredients": "Masa 100% ma\xEDz molido, rellenas de carne de Vacuno \u{1F969} sal. patata cocida y un sofrito tradicional.",
    "preparation": " Fre\xEDr en aceite a 180\xB0C por 12 min, aproximadamente. No hace falta descongelar el producto para fre\xEDrlo. ",
    "conservation": "Conservar congelado a -18\xB0C. No recongelar una vez descongelado.",
    "price": 10.9,
    "originalPrice": null,
    "memberPrice": 8.9,
    "packSize": "6 unidades",
    "weight": "450 g",
    "format": "13,5 cm (6 unidades)",
    "soldOut": false,
    "badge": null
  },
  {
    "id": "2",
    "slug": "empanadas-grandes-pack-10",
    "name": "Empanadas Grandes de Carne Ternera      \nx10 und",
    "category": "Empanadas",
    "description": "\u{1F9CA} CONGELADAS \xB7 Pack de 10 empanadas colombianas grandes de 13,5 cm. Perfectas para reuniones y celebraciones familiares.",
    "ingredients": "Masa 100% ma\xEDz molido, rellenas de carne de Vacuno \u{1F969} sal. patata cocida y un sofrito tradicional.",
    "preparation": " Fre\xEDr en aceite a 180\xB0C por 12 min, aproximadamente. No hace falta descongelar el producto para fre\xEDrlo. ",
    "conservation": "Conservar congelado a -18\xB0C. No recongelar una vez descongelado.",
    "price": 17.9,
    "originalPrice": null,
    "memberPrice": 16.99,
    "packSize": "10 unidades",
    "weight": "750 g",
    "format": "13,5 cm (10 unidades)",
    "soldOut": false,
    "badge": "top"
  },
  {
    "id": "25",
    "slug": "empanadas-grandes-pollo-pack-10",
    "name": "Empanadas Grandes de Pollo x10 und",
    "category": "Empanadas",
    "description": "\u{1F9CA} CONGELADAS \xB7 Pack de 10 empanadas colombianas grandes de pollo mechado. Masa crujiente de ma\xEDz 100% y relleno jugoso de pollo desmechado.",
    "ingredients": "Masa 100% ma\xEDz molido, rellenas de Pollo, \u{1F413} sal. patata cocida y un sofrito tradicional.",
    "preparation": " Fre\xEDr en aceite a 180\xB0C por 12 min, aproximadamente. No hace falta descongelar el producto para fre\xEDrlo. ",
    "conservation": "Conservar congelado a -18\xB0C. No recongelar una vez descongelado.",
    "price": 16.99,
    "originalPrice": 17.9,
    "memberPrice": 16.49,
    "packSize": "10 unidades",
    "weight": "750 g",
    "format": "13,5 cm (10 unidades)",
    "soldOut": false,
    "badge": "oferta"
  },
  {
    "id": "8",
    "slug": "empanadas-cocteleras-pack-17-pollo",
    "name": "Empanadas de POLLO Peque\xF1as Cocteleras x17 und",
    "category": "Empanadas",
    "description": "\u{1F9CA} CONGELADAS \xB7 Mini empanadas colombianas tipo c\xF3ctel de 8 cm. Perfectas como aperitivo o snack. Tama\xF1o bocado, sabor gigante.",
    "ingredients": "Masa 100% ma\xEDz molido, rellenas de Pollo, \u{1F413} sal. patata cocida y un sofrito tradicional.",
    "preparation": "Fre\xEDr en aceite a 180\xB0C por 12 min, aproximadamente. No hace falta descongelar el producto para fre\xEDrlo.",
    "conservation": "Conservar congelado a -18\xB0C. No recongelar una vez descongelado.",
    "price": 14.9,
    "originalPrice": null,
    "memberPrice": 13.99,
    "packSize": "17 unidades",
    "weight": "510 g",
    "format": "8 cm (17 unidades)",
    "soldOut": false,
    "badge": "nuevo"
  },
  {
    "id": "26",
    "slug": "empanadas-cocteleras-pack-17-ternera",
    "name": "Empanadas de Ternera Carne Peque\xF1as Cocteleras x17 und",
    "category": "Empanadas",
    "description": "\u{1F9CA} CONGELADAS \xB7 Mini empanadas colombianas tipo c\xF3ctel de 8 cm. Perfectas como aperitivo o snack. Tama\xF1o bocado, sabor gigante.",
    "ingredients": "Masa 100% ma\xEDz molido, rellenas de carne de Vacuno \u{1F969} sal. patata cocida y un sofrito tradicional.",
    "preparation": "Fre\xEDr en aceite a 180\xB0C por 12 min, aproximadamente. No hace falta descongelar el producto para fre\xEDrlo.",
    "conservation": "Conservar congelado a -18\xB0C. No recongelar una vez descongelado.",
    "price": 14.9,
    "originalPrice": null,
    "memberPrice": 13.99,
    "packSize": "17 unidades",
    "weight": "510 g",
    "format": "8 cm (17 unidades)",
    "soldOut": false,
    "badge": "nuevo"
  },
  {
    "id": "7",
    "slug": "arepas-queso-pack-6",
    "name": "Arepa Rellena de Queso Mozzarella x5 und",
    "category": "Arepas",
    "description": "\u{1F9CA} CONGELADAS \xB7 Arepas de ma\xEDz rellenas de queso mozzarella fundido. La base de la cocina colombiana y venezolana. 5 unidades por paquete.",
    "ingredients": "Harina de ma\xEDz precocida, queso mozzarella, mantequilla, sal, agua.",
    "preparation": "Plancha/sart\xE9n: 4 min por lado a fuego medio. Horno: 200\xB0C por 12 min. Air fryer: 180\xB0C por 10 min.",
    "conservation": "Conservar congelado a -18\xB0C. No recongelar una vez descongelado.",
    "price": 6.9,
    "originalPrice": null,
    "memberPrice": 6.1,
    "packSize": "5 unidades",
    "weight": "700 g",
    "format": "5 unidades",
    "soldOut": false,
    "badge": "oferta"
  },
  {
    "id": "15",
    "slug": "arepa-chocolo-queso-pack-4",
    "name": "Arepa de Ch\xF3colo con Queso Colombiana x4 und",
    "category": "Arepas",
    "description": "\u{1F9CA} CONGELADA \xB7 Arepa de ch\xF3colo (hecha con ma\xEDz tierno molido) Rellena con queso latino, de sabor suave y un toque dulcecito, ideal para desayuno o merienda. Producto ultracongelado a -18\xB0C para preservar todo su sabor y textura artesanal. Llega a tu casa en perfecto estado, listo para que lo prepares cuando quieras. Sin conservantes artificiales.",
    "ingredients": "Ma\xEDz tierno (ch\xF3colo), queso latino, mantequilla, sal, az\xFAcar.",
    "preparation": "Plancha/sart\xE9n: 4-5 min por lado a fuego medio. Horno: 200\xB0C por 12 min.",
    "conservation": "Conservar congelado a -18\xB0C. No recongelar una vez descongelado.",
    "price": 7.7,
    "originalPrice": null,
    "memberPrice": 7.1,
    "packSize": "4 unidades",
    "weight": "500 g",
    "format": "4 unidades",
    "soldOut": false,
    "badge": "nuevo"
  },
  {
    "id": "16",
    "slug": "arepa-artesanal-rellenar-pack-6",
    "name": "Arepa Artesanal para Rellenar x6 und",
    "category": "Arepas",
    "description": "\u{1F9CA} CONGELADA \xB7 Arepa artesanal para rellenar de Dcarnilsa, con textura firme y sabor neutro. Paquete de 6 unidades, ideal para recetas rellenas y uso profesional.",
    "ingredients": "Harina de ma\xEDz precocida, agua, sal.",
    "preparation": "Plancha/sart\xE9n: 4 min por lado a fuego medio. Horno: 200\xB0C por 12 min. Air fryer: 180\xB0C por 10 min.",
    "conservation": "Conservar congelado a -18\xB0C. No recongelar una vez descongelado.",
    "price": 3.9,
    "originalPrice": null,
    "memberPrice": 3.2,
    "packSize": "6 unidades",
    "weight": "800 g",
    "format": "6 unidades",
    "soldOut": true,
    "badge": null
  },
  {
    "id": "10",
    "slug": "chorizo-santarosano-pack-10",
    "name": "Chorizo Peque\xF1o Santarosano x10 und",
    "category": "Chorizos",
    "description": "\u{1F9CA} CONGELADO \xB7 Aut\xE9ntico chorizo colombiano santarosano de 7,5 cm. Pack de 10 unidades. Sabor tradicional ahumado, perfecto para asar a la parrilla.",
    "ingredients": "Carne de cerdo, especias naturales, ajo, cebolla, comino, sal, tripa natural.",
    "preparation": "Parrilla/plancha: 8-10 min a fuego medio. Horno: 200\xB0C por 15 min. Sart\xE9n: 6-8 min.",
    "conservation": "Conservar congelado a -18\xB0C. No recongelar una vez descongelado.",
    "price": 7.9,
    "originalPrice": null,
    "memberPrice": 7.1,
    "packSize": "10 unidades",
    "weight": "500 g",
    "format": "7,5 cm (10 und)",
    "soldOut": false,
    "badge": "top"
  },
  {
    "id": "11",
    "slug": "chorizo-xl-pack-5",
    "name": "Chorizo XL Santarosano x5 und",
    "category": "Chorizos",
    "description": "\u{1F9CA} CONGELADO \xB7 Chorizo colombiano santarosano tama\xF1o XL de 22 cm. Pack de 5 unidades. Ideal para asados y parrilladas.",
    "ingredients": "Carne de cerdo, especias naturales, ajo, cebolla, comino, sal, tripa natural.",
    "preparation": "Parrilla/plancha: 12-15 min a fuego medio. Horno: 200\xB0C por 20 min.",
    "conservation": "Conservar congelado a -18\xB0C. No recongelar una vez descongelado.",
    "price": 12.9,
    "originalPrice": null,
    "memberPrice": 11.99,
    "packSize": "5 unidades",
    "weight": "800\u20131000 g",
    "format": "22 cm (5 und)",
    "soldOut": false,
    "badge": "nuevo"
  },
  {
    "id": "12",
    "slug": "salchichon-cervecero",
    "name": "Salchich\xF3n Cervecero",
    "category": "Embutidos",
    "description": "\u{1F9CA} CONGELADO \xB7 Salchich\xF3n cervecero colombiano de 27,5 cm. El acompa\xF1ante perfecto para una cerveza fr\xEDa. Aut\xE9ntico sabor D'Carnilsa.",
    "ingredients": "Carne de cerdo, carne de res, especias, sal, conservantes permitidos.",
    "preparation": "Fre\xEDr en rodajas: 3-4 min por lado. Plancha: 5 min. Ideal como acompa\xF1amiento o snack.",
    "conservation": "Conservar congelado a -18\xB0C. No recongelar una vez descongelado.",
    "price": 8.5,
    "originalPrice": null,
    "memberPrice": 7,
    "packSize": "1 unidad",
    "weight": "580 g",
    "format": "27,5 cm",
    "soldOut": false,
    "badge": null
  },
  {
    "id": "13",
    "slug": "salchicha-ranchera-pack-10",
    "name": "Salchicha Ranchera Ahumada x10 und",
    "category": "Embutidos",
    "description": "\u{1F9CA} CONGELADO \xB7 Salchichas rancheras ahumadas colombianas de 11 cm. Pack de 10 unidades. Sabor ahumado aut\xE9ntico marca D'Carnilsa.",
    "ingredients": "Carne de cerdo, carne de res, especias, sal, humo natural, conservantes permitidos.",
    "preparation": "Hervir: 5 min. Fre\xEDr/plancha: 4-5 min. Ideal con arepa y hogao.",
    "conservation": "Conservar congelado a -18\xB0C. No recongelar una vez descongelado.",
    "price": 7.5,
    "originalPrice": null,
    "memberPrice": 6,
    "packSize": "10 unidades",
    "weight": "400 g",
    "format": "11 cm (10 und)",
    "soldOut": false,
    "badge": null
  },
  {
    "id": "14",
    "slug": "salami-latino",
    "name": "Salami Latino",
    "category": "Embutidos",
    "description": "\u{1F9CA} CONGELADO \xB7 Salami latino estilo dominicano de 15 cm. Vers\xE1til para s\xE1ndwiches, acompa\xF1amientos o frito. Marca Rivera Super Especial.",
    "ingredients": "Carne de cerdo, carne de res, especias, sal, conservantes permitidos.",
    "preparation": "Cortar en rodajas y fre\xEDr: 2-3 min por lado. Ideal frito con queso o en s\xE1ndwich.",
    "conservation": "Conservar congelado a -18\xB0C. No recongelar una vez descongelado.",
    "price": 7.9,
    "originalPrice": null,
    "memberPrice": 6.5,
    "packSize": "1 unidad",
    "weight": "500 g",
    "format": "15 cm",
    "soldOut": false,
    "badge": null
  },
  {
    "id": "5",
    "slug": "pandebonos-pack-6",
    "name": "Pandebono Colombiano x6 und",
    "category": "PandeBono",
    "description": "\u{1F9CA} CONGELADO \xB7 Bollitos de yuca y queso, esponjosos y con ese sabor colombiano inconfundible. Perfectos para el desayuno o la merienda.",
    "ingredients": "Almid\xF3n de yuca, queso coste\xF1o, huevo, mantequilla, sal.",
    "preparation": "Horno: 180\xB0C por 18 min. Air fryer: 170\xB0C por 15 min.",
    "conservation": "Conservar congelado a -18\xB0C. No recongelar una vez descongelado.",
    "price": 7.9,
    "originalPrice": null,
    "memberPrice": 6.5,
    "packSize": "6 unidades",
    "weight": "360 g",
    "format": "6 und",
    "soldOut": false,
    "badge": null
  },
  {
    "id": "4",
    "slug": "tequenos-pack-14",
    "name": "Teque\xF1os de Queso - Pack 14",
    "category": "Teque\xF1os",
    "description": "\u{1F9CA} CONGELADO \xB7 Crujientes palitos de masa rellenos de queso fundente. El snack venezolano m\xE1s adictivo.",
    "ingredients": "Harina de trigo, queso semiduro, mantequilla, huevo, sal, az\xFAcar.",
    "preparation": "Horno: 190\xB0C por 12 min. Air fryer: 180\xB0C por 10 min. Fre\xEDr: aceite a 180\xB0C por 4 min.",
    "conservation": "Conservar congelado a -18\xB0C. No recongelar una vez descongelado.",
    "price": 14.9,
    "originalPrice": null,
    "memberPrice": 12.99,
    "packSize": "14 unidades",
    "weight": null,
    "format": null,
    "soldOut": true,
    "badge": null
  },
  {
    "id": "6",
    "slug": "bunuelos-pack-6",
    "name": "Bu\xF1uelos Colombianos - Pack 6",
    "category": "Bu\xF1uelos",
    "description": "\u{1F9CA} CONGELADO \xB7 Bolitas de queso fritas, crujientes por fuera y suaves por dentro. Tradici\xF3n colombiana en cada bocado.",
    "ingredients": "Almid\xF3n de ma\xEDz, queso fresco, huevo, az\xFAcar, sal, polvo de hornear.",
    "preparation": "Fre\xEDr: aceite a 170\xB0C por 6 min (dorar por todos los lados). Horno: 190\xB0C por 15 min.",
    "conservation": "Conservar congelado a -18\xB0C. No recongelar una vez descongelado.",
    "price": 7.7,
    "originalPrice": null,
    "memberPrice": 14.99,
    "packSize": "6 unidades",
    "weight": null,
    "format": null,
    "soldOut": true,
    "badge": null
  },
  {
    "id": "20",
    "slug": "combo-1-empanadas-pequenas-fritas",
    "name": "Combo 1 / Hay 17 Empanadas Peque\xF1as Fritas",
    "category": "Combos",
    "description": "\u{1F525} LISTAS PARA CONSUMIR \xB7 17 empanadas peque\xF1as fritas, listas para disfrutar. Incluye domicilio en Zaragoza capital.",
    "ingredients": "Masa 100% ma\xEDz molido, rellenas de carne de Vacuno /pollo, patata cocida, cebolla, ajo, comino, sal.",
    "preparation": "\xA1Ya vienen fritas y listas! Solo calentar si lo deseas: microondas 1 min o horno 5 min a 180\xB0C.",
    "conservation": "Consumir en el d\xEDa. Se pueden recalentar.",
    "price": 19.99,
    "originalPrice": null,
    "memberPrice": 17.9,
    "packSize": "17 unidades",
    "weight": null,
    "format": null,
    "soldOut": false,
    "badge": null
  },
  {
    "id": "21",
    "slug": "combo-2-empanadas-grandes-fritas",
    "name": "Combo 2 \u2014 10 Empanadas Grandes Fritas",
    "category": "Combos",
    "description": "\u{1F525} LISTAS PARA CONSUMIR \xB7 10 empanadas grandes fritas, listas para disfrutar. Incluye domicilio en Zaragoza capital.",
    "ingredients": "Masa 100% ma\xEDz molido, rellenas de carne de Vacuno /pollo, patata cocida, cebolla, ajo, comino, sal.",
    "preparation": "\xA1Ya vienen fritas y listas! Solo calentar si lo deseas: microondas 1 min o horno 5 min a 180\xB0C.",
    "conservation": "Consumir en el d\xEDa. Se pueden recalentar.",
    "price": 22.99,
    "originalPrice": 23.9,
    "memberPrice": 20.9,
    "packSize": "10 unidades",
    "weight": null,
    "format": null,
    "soldOut": false,
    "badge": "oferta"
  },
  {
    "id": "22",
    "slug": "combo-3-mixto-fritas",
    "name": "Combo 3 \u2014 Mixto (10 Grandes + 17 Peque\xF1as) Fritas",
    "category": "Combos",
    "description": "\u{1F525} LISTAS PARA CONSUMIR \xB7 Combo mixto: 10 empanadas grandes + 17 peque\xF1as, todas fritas. Incluye domicilio en Zaragoza capital.",
    "ingredients": "Masa 100% ma\xEDz molido, rellenas de carne de Vacuno /pollo, patata cocida, cebolla, ajo, comino, sal.",
    "preparation": "\xA1Ya vienen fritas y listas! Solo calentar si lo deseas.",
    "conservation": "Consumir en el d\xEDa. Se pueden recalentar.",
    "price": 29.99,
    "originalPrice": null,
    "memberPrice": 27,
    "packSize": "27 unidades",
    "weight": null,
    "format": null,
    "soldOut": false,
    "badge": "oferta"
  },
  {
    "id": "23",
    "slug": "combo-4-empanadas-pequenas-fritas",
    "name": "Combo 4__ +51 Empanadas Peque\xF1as Fritas",
    "category": "Combos",
    "description": "\u{1F525} LISTAS PARA CONSUMIR \xB7 \xA1Mega combo! 51 empanadas peque\xF1as fritas para fiestas and eventos. Incluye domicilio en Zaragoza capital.",
    "ingredients": "Masa 100% ma\xEDz molido, rellenas de carne de Vacuno /pollo, patata cocida, cebolla, ajo, comino, sal.",
    "preparation": "\xA1Ya vienen fritas y listas! Solo calentar si lo deseas.",
    "conservation": "Consumir en el d\xEDa. Se pueden recalentar.",
    "price": 46.99,
    "originalPrice": null,
    "memberPrice": 39.9,
    "packSize": "51 unidades",
    "weight": null,
    "format": null,
    "soldOut": false,
    "badge": null
  },
  {
    "id": "24",
    "slug": "combo-xxl-mixto-salami-arepas",
    "name": "Combo XXL : 10 Empanadas Grandes + Salami Latino + 3 Arepas + Salsas Aj\xED + Domicilio GRATIS",
    "category": "Combos",
    "description": "\u{1F525} LISTAS PARA CONSUMIR \xB7 El combo definitivo: 10 empanadas grandes + 17 peque\xF1as fritas + salami + 3 arepas de queso. Incluye domicilio en Zaragoza capital.",
    "ingredients": "Masa 100% ma\xEDz molido, rellenas de carne de Vacuno /pollo, patata cocida, cebolla, ajo, comino, sal.",
    "preparation": "\xA1Ya vienen fritas y listas! Solo calentar si lo deseas.",
    "conservation": "Consumir en el d\xEDa. Se pueden recalentar.",
    "price": 39.99,
    "originalPrice": null,
    "memberPrice": 35.99,
    "packSize": "30+ unidades",
    "weight": null,
    "format": null,
    "soldOut": false,
    "badge": "nuevo"
  },
  {
    "id": "29",
    "slug": "combo-valluno-champus-empanadas",
    "name": "Combo Valluno \u2014 Champ\xFAs + 2 Empanadas Grandes de Vacuno + Chorizo Santarrosano",
    "category": "Combos",
    "description": "\u{1F525} OFERTA ESPECIAL \xB7 Aut\xE9ntico Combo Valluno: 1 Champ\xFAs Valluno tradicional (bebida de ma\xEDz, lulo, pi\xF1a y panela) + 2 empanadas grandes de ternera reci\xE9n fritas + 1 chorizo santarrosano a la parrilla. Sabor 100% colombiano del Valle del Cauca.",
    "ingredients": "Champ\xFAs: ma\xEDz, lulo, pi\xF1a, panela, canela, hojas de naranjo agrio. Empanadas: harina de ma\xEDz, carne de Vacuno, papa, cebolla, ajo, comino, sal. Chorizo: carne de cerdo, especias naturales, ajo, comino, sal.",
    "preparation": "\xA1Listo para disfrutar! Champ\xFAs servir fr\xEDo. Empanadas y chorizo calentar 1 min en microondas o 5 min en horno a 180\xB0C.",
    "conservation": "Consumir en el d\xEDa. Mantener champ\xFAs refrigerado.",
    "price": 12.99,
    "originalPrice": null,
    "memberPrice": 11.99,
    "packSize": "1 combo (champ\xFAs + 2 empanadas + chorizo)",
    "weight": null,
    "format": null,
    "soldOut": false,
    "badge": "oferta"
  },
  {
    "id": "27",
    "slug": "pastel-gloria",
    "name": "Pastel Gloria D'Carnilsa",
    "category": "Hojaldres",
    "description": "\u{1F9CA} CONGELADO \xB7 Pastel Gloria D'Carnilsa, hojaldre tradicional colombiano relleno, suave y dorado. Ideal para el desayuno o la merienda.",
    "ingredients": "Harina de trigo, mantequilla, huevo, az\xFAcar, relleno tradicional, sal.",
    "preparation": "Horno: 180\xB0C por 15-18 min. Air fryer: 170\xB0C por 12 min.",
    "conservation": "Conservar congelado a -18\xB0C. No recongelar una vez descongelado.",
    "price": 14.9,
    "originalPrice": null,
    "memberPrice": 13.5,
    "packSize": "6 unidades",
    "weight": null,
    "format": null,
    "soldOut": false,
    "badge": "nuevo"
  },
  {
    "id": "28",
    "slug": "chicharron-dulce-guayaba",
    "name": "Chicharr\xF3n de Dulce de Guayaba D'Carnilsa",
    "category": "Hojaldres",
    "description": "\u{1F9CA} CONGELADO \xB7 Chicharr\xF3n de hojaldre D'Carnilsa relleno de dulce de guayaba. Crujiente por fuera y dulce por dentro, un cl\xE1sico colombiano.",
    "ingredients": "Harina de trigo, mantequilla, huevo, dulce de guayaba, az\xFAcar, sal.",
    "preparation": "Horno: 180\xB0C por 15 min. Air fryer: 170\xB0C por 12 min.",
    "conservation": "Conservar congelado a -18\xB0C. No recongelar una vez descongelado.",
    "price": 10.5,
    "originalPrice": null,
    "memberPrice": 9.5,
    "packSize": "1 paquete",
    "weight": null,
    "format": null,
    "soldOut": false,
    "badge": "nuevo"
  }
];

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "Listar productos MaxRico",
  description: "Devuelve el cat\xE1logo de productos artesanales colombianos (empanadas, teque\xF1os, PandeBono, arepas, chorizos, etc.) con precio normal, precio socio y disponibilidad.",
  inputSchema: {
    category: z.string().optional().describe("Filtro opcional por categor\xEDa (ej: Empanadas, PandeBono, Arepas)."),
    onlyAvailable: z.boolean().optional().describe("Si es true, excluye productos agotados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, onlyAvailable }) => {
    const filtered = products.filter((p) => {
      if (category && p.category.toLowerCase() !== category.toLowerCase()) return false;
      if (onlyAvailable && p.soldOut) return false;
      return true;
    });
    const rows = filtered.map((p) => ({
      id: p.id,
      slug: p.slug,
      name: p.name,
      category: p.category,
      price_eur: p.price,
      member_price_eur: p.memberPrice,
      pack_size: p.packSize,
      weight: p.weight ?? null,
      sold_out: !!p.soldOut
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { products: rows }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Detalle de producto",
  description: "Devuelve la ficha completa de un producto MaxRico por slug o id: descripci\xF3n, ingredientes, preparaci\xF3n, conservaci\xF3n, precios y disponibilidad.",
  inputSchema: {
    slugOrId: z2.string().min(1).describe("Slug o id del producto.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slugOrId }) => {
    const key = slugOrId.toLowerCase();
    const p = products.find(
      (x) => x.slug.toLowerCase() === key || x.id.toLowerCase() === key
    );
    if (!p) {
      return {
        content: [{ type: "text", text: `No se encontr\xF3 ning\xFAn producto con "${slugOrId}".` }],
        isError: true
      };
    }
    const row = {
      id: p.id,
      slug: p.slug,
      name: p.name,
      category: p.category,
      description: p.description,
      ingredients: p.ingredients,
      preparation: p.preparation,
      conservation: p.conservation,
      price_eur: p.price,
      original_price_eur: p.originalPrice ?? null,
      member_price_eur: p.memberPrice,
      pack_size: p.packSize,
      weight: p.weight ?? null,
      format: p.format ?? null,
      sold_out: !!p.soldOut,
      badge: p.badge ?? null,
      url: `https://maxrico.es/producto/${p.slug}`
    };
    return {
      content: [{ type: "text", text: JSON.stringify(row, null, 2) }],
      structuredContent: { product: row }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "Listar categor\xEDas",
  description: "Devuelve las categor\xEDas del cat\xE1logo MaxRico y el n\xFAmero de productos en cada una.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const counts = categories.map((c) => ({
      category: c,
      count: products.filter((p) => p.category === c).length
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(counts, null, 2) }],
      structuredContent: { categories: counts }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "maxrico-mcp",
  title: "MaxRico \u2014 Cat\xE1logo",
  version: "0.1.0",
  instructions: "Herramientas de solo lectura del cat\xE1logo de MaxRico (gastronom\xEDa artesanal colombiana, 100% ma\xEDz molido, sin gluten). Usa list_categories y list_products para explorar el cat\xE1logo, y get_product para la ficha completa. Los pedidos se hacen en https://maxrico.es o por WhatsApp +34 695798632.",
  tools: [list_products_default, get_product_default, list_categories_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
